### ISSUE TITLE
Download files weird headings

### ISSUE THREAD

**Issue by HedvigS** [clld/clld#120]
the download files on several CLLD-apps tables have different headings and order than the columns the webpage has. this is confusing. "Representation" for "how many features are filled in" etc. Uniformity would be nice if possible. I understand how this came about, just suggesting a change. Apologies for bothering.

**Comment by xrotwang** [comment]
It's actually not only different headings and order, but often also different content altogether. The reason for this is mostly performance: While the dynamic tables on the web page only display a fraction of the rows (by default 100), the CSV download will contain up to 2000. Therefore including the columns derived from other tables which need to be joined isn't an option. Thus, the CSV download only contains the columns of the "raw" table - no related columns from other tables. So I'd say anything that hints at the CSV and the table on the web page being different is actually a feature rather than a bug.
