### ISSUE TITLE
DownloadWidget: sort the adapters

### ISSUE THREAD

**Issue by pavelsof** [clld/clld#130]
The data tables come with a downloads drop-down allowing the user to export the data in several formats. The list of these formats is in seemingly arbitrary order which also varies from table to table and from project to project. Obviously nothing serious, but it is unpleasantly inconsistent.

A possible fix might be to insert something like this after line 59 of `clld/web/util/downloadwidget.py`:
```python
        adapters = sorted(adapters, key=lambda x: x.extension)
```
As it is a presentation issue, it makes sense to introduce sorting in the `DownloadWidget` as opposed to, e.g., the registry.

**Comment by xrotwang** [comment]
Good suggestion! I guess it would also be useful, to have a way to filter the available downloads per DataTable (because often the default implementations don't add much value). Presumably this would have to happen somewhere in `clld.web.datatables.base.Toolbar`, based on info passed in from the `DataTable` when instantiating the `Toolbar`.
