### ISSUE TITLE
Link outdated

### ISSUE THREAD

**Issue by NerdsvilleCEO** [clld/clld#171]
This link appears to be outdated, as a new contributor I would like to figure out where to find the source :)

https://doi.org/10.5281/zenodo.592412

**Comment by chrzyki** [comment]
Heya @NerdsvilleCEO,

Zenodo archives certain release versions of CLLD and provides them/us with a DOI, e.g. for making specific versions easily referable in publications. The most up-to-date code can always be found in the CLLD repository, i.e. the repository this issue was created in: [clld/clld](https://github.com/clld/clld).
