### ISSUE TITLE
greedy and non-case sensitive tables in web apps?

### ISSUE THREAD

**Issue by HedvigS** [clld/clld#191]
I wasn't sure where to put this, but is it very tricky to make the interactive tables filtering function greedy and non-case sensitive. I.e. so that writing "252" or "gb252" gives "GB252" in the features table on the Grambank web-app for example?

Just a thought, as a person who has clicked my way through these sites for a while, I've always wondered this. 

Thanks!

**Comment by xrotwang** [comment]
It is not. In fact, the behaviour you describe as "greedy and non-case sensitive" is rather the default, and used for example for the "Feature" title column at https://grambank.clld.org/parameters
For ID columns, clld apps typically use an exact match, since IDs often are something that you either know exactly or you don't at all. If you think we should change this for grambank, please open an issue at https://github.com/clld/grambank
