### ISSUE TITLE
Support for IPA charts

### ISSUE THREAD

**Issue by xrotwang** [clld/clld#211]
Idea: Fill in the standard IPA charts with segments categorized by feature vectors.
- [template](https://github.com/clld/phoible/blob/master/phoible/templates/ipa.mako)
  - consonants (pulmonic) are slotted via `place` and `manner`
  - conconants (non-pulmonic) are categorized as `clicks` or `voiced implosives` and `place`
  - vowels categorized by ?
- A `Segments` class - basically a `list` with filtered access to CLTS like `Sound`s, which can be passed to the template for rendering. 
- A `Sound` needs
  - a method to turn itself into a link
  - a glyph
  - a feature vector for filtering.

**Comment by xrotwang** [comment]
Thinking a bit more about this, this should probably be a package that only relies on `pyclts` - basically a visualization component for `pyclts`. @LinguList : thoughts?

**Comment by LinguList** [comment]
Yes. if you check out the edictor template for sounds, this is more complete than the one in phoible by now, e.g., for [German](http://digling.org/edictor/plugouts/ipa_chart.html?doculect=German&sound_list=a%2Cau%2Cai%2Ca%CB%90%2Ca%CB%90%C9%99%2Cb%2Cd%2Ce%CB%90%2Ce%CB%90%C9%99%2Cf%2Ch%2Ci%CB%90%2Cj%2Ck%2Cl%2Cm%2Cn%2Co%CB%90%2Cpf%2Cp%2Cr%2Cs%2Cts%2Ct%2Cu%CB%90%2Cv%2Cx%2Cy%CB%90%2Cz%2C%C3%B8%CB%90%2C%C5%8B%2C%C9%94%2C%C9%94y%C9%99%2C%C9%94y%2C%C9%99%2C%C9%9B%2C%C9%A1%2C%C9%AA%2C%CA%83%2C%CA%8A%2C%CA%8F).

The template complete is [here](http://digling.org/edictor/plugouts/ipa_chart.html).

**Comment by LinguList** [comment]
I think, this is something for clts-people, like @tresoldi or @cormacanderson, who should help in designing an improved chart. Diphtongs will be difficult, but even that may be useful in chart-like form...

**Comment by bambooforest** [comment]
http://eurasianphonology.info/segments 

treats such things in an interpretable format (well except for many diphthongs :)

**Comment by xrotwang** [comment]
@bambooforest I was wondering for some time, whether people actually use the visual cues of the IPA charts (and in particular the vowel trapezoid) to think about inventories or systems of phonemes (somehow along the lines of "there's something missing at the top left - curious ..."). If so, I'd see the value of the charts. But if you think the categorization at eurasianphonology is more interpretable, then it seems any tabular form that can be filtered by features will do.

**Comment by xrotwang** [comment]
@LinguList What I said above also applies to the idea of an "improved chart". The main (only?) benefit of these charts I see, is as a better way of getting information about the whole inventory into ones head. This better way probably relies heavily on what one is used to - so any improvement may at least have detrimental side effects.

**Comment by LinguList** [comment]
Yes, maybe much better :)

**Comment by bambooforest** [comment]
@xrotwang -- i think linguists use the IPA charts all the time for the types of visualization impressions that you just mentioned, e.g. wow, this language doesn't have any low vowels, just front and back high vowels. this can lead to further investigation and research into the why. 

to that extent, i'm very happy with how the IPA charts look on phoible.org and i would like to keep them as is.

i only mention eurasian phonologies because i find their consonant charts easier on the eye than the edictor charts (but that's probably because of the colors - the red really stands out; the blue looks like it should be clickable).

on the other hand, there's something very appealing about the vowel diagrams in the edictor charts that's missing in the eurasian vowel charts (i find the latter harder to interpret).

**Comment by LinguList** [comment]
@xrotwang, there is one clearcut important aspect of charts: they show you gaps in your system, and the system's symmetries. So if you have the same nasal vowels as normal vowels, or if you have the same voiced stops as unvoiced stops.

**Comment by LinguList** [comment]
> i only mention eurasian phonologies because i find their consonant charts easier on the eye than the edictor charts (but that's probably because of the colors - the red really stands out; the blue looks like it should be clickable).

I was using the wikipedia page for the edictor charts, that's why I mentioned that I would be happy if somebody would make a better one, really, because we need bigger ones, and the style in phoible is often disappointing, with half of the symbols being left-overs, so it would be good to have more coverage there, and with our unified clts feature system it should not be too hard to think of a way to assemble all sounds that are not clusters or diphthongs...

**Comment by xrotwang** [comment]
Yes, I guess it would be useful if more of the inventory could be
integrated in the diagrams, then.

Johann-Mattis List <notifications@github.com> schrieb am Do., 14. Mai 2020,
11:38:

**Comment by xrotwang** [comment]
So we seem to agree then that diagrams of the phoible or edictor kind would be good, but slotting in phonemes should be done not whitelist-based but feature based, right?

**Comment by bambooforest** [comment]
This is probably one of the worst case scenarios in phoible:

https://phoible.org/inventories/view/1379#tipa

Not only are there tons of clicks, but as Mattis points out, there are bunch of "basic" phonemes, such as aspirated, ejective, and dental ejective, stops, that end up in the "other segments" category, which makes it difficult to visually inspect for gaps in the phonological inventory.

http://eurasianphonology.info/segments deals with this by either packing in certain variants into the Plain Series or by breaking them out into separate charts (e.g. labialized, velarized, etc.).

https://en.wikipedia.org/wiki/International_Phonetic_Alphabet_chart / edictor deal with this by expanding the manner and place features. 

Tbh I don't think there's any sanctioned or best practice approach to extending the charts for complete coverage. And as far as I'm aware, certainly not from the IPA.

Perhaps best then would be to add place/manner features and insert symbols, but my impression is that this should probably be informed by segment frequency. For example, a chart could make place for <pʷʰ> but this only occurs (so far) in two languages. On the other hand, <pʰ> occurs all over the place.

@drammock -- do you have an opinion?

**Comment by xrotwang** [comment]
Extending "manner" with extra rows - as necessary - is probably ok, since this will not interfere much with the visual pattern. With "place" this might be more difficult, since "place" is ordered and we wouldn't just want to add extra columns on the right, correct?

**Comment by LinguList** [comment]
Yes, @xrotwang, and we should not need much more.

I think, as @bambooforest mentions, frequency should count, and aspiration is extremely frequent, but not covered in many templates (edictor has it in fact, because it was annoying me in the past, that I would not capture these cases, as you can see [here](http://digling.org/edictor/plugouts/ipa_chart.html?doculect=German&sound_list=d%CA%B1%2Ct%CA%B0%2Ca%2Cau%2Cai%2Ca%CB%90%2Ca%CB%90%C9%99%2Cb%2Cd%2Ce%CB%90%2Ce%CB%90%C9%99%2Cf%2Ch%2Ci%CB%90%2Cj%2Ck%2Cl%2Cm%2Cn%2Co%CB%90%2Cpf%2Cp%2Cr%2Cs%2Cts%2Ct%2Cu%CB%90%2Cv%2Cx%2Cy%CB%90%2Cz%2C%C3%B8%CB%90%2C%C5%8B%2C%C9%94%2C%C9%94y%C9%99%2C%C9%94y%2C%C9%99%2C%C9%9B%2C%C9%A1%2C%C9%AA%2C%CA%83%2C%CA%8A%2C%CA%8F)). 

So we could start by making a frequency analysis, or we could rather trust our "instincts"? 

I'd say, from clts-perspective:

1. dipthongs should be listed in a chart called "dipthongs"
2. cluster consonants (like `kp` together) should be listed in a chart called "clusters" or any other name.
3. clicks would need their own chart, but they can also be unordered, maybe
4. we want aspiration, plain, voiced, breathy-voiced as four-kind-representations for consonants
5. vowels need a short, a long, and a nasal chart, maybe short/long can be displayed in the same
6. for tones, I'd follow for the time being the schema I set up in edictor, as there's no real alternative

**Comment by drammock** [comment]
Some thoughts:

1. I'm actually not a huge fan of the vowel trapezoid as a way of displaying vowel phonemes, but I agree with @bambooforest that, as far as I can tell, most linguists like it. Having a series of trapezoids for oral, nasal, and diphthong/triphthong phonemes seems sensible to me (provided they are smaller than the current version on phoible.org).  Voice quality (breathy/creaky) probably needs its own trapezoid (or two for some inventories). If possible I'd put vowel length contrasts onto the oral, nasal, and voice quality charts where appropriate.  I'd probably want any trapezoid that was completely empty for a given doculect to be hidden, rather than taking up space.

2. An idea for the coronal consonants is to have top-level columns "apical" and "laminal" and have each of the coronal place columns nested under those. I.e.:

```
+-----------------------------------------+-----------------------------------------+
|               apical                    |              laminal                    |
+-----------------------------------------+-----------------------------------------+
| dent | alv | post-alv | alv-pal | retro | dent | alv | post-alv | alv-pal | retro |
+-----------------------------------------+-----------------------------------------+
```

3. adding separate "manner" rows for ejectives, velar-backed clicks, and uvular-backed clicks seems easy enough. I'd actually put those rows at the *top* of the chart so they're adjacent to the pulmonic plosives. I'd also add a row for "aspirated plosives" that had voiceless aspirated and breathy-voiced stops as its voiceless/voiced pair.

4. Coming up with a fully articulated plan in advance may not be possible / efficient.  I can see two broad approaches to being data-driven here:
    - start with a handful of the very largest inventories; pick one and adapt the chart to accommodate it as best as we are able; then tweak the chart to accommodate the next largest inventory; then iterate until satisfied or sick of it.
    - start with the first 50 most frequent phonemes across phoible and adapt the chart to accommodate them; then try to accommodate the next 10; then the next 10; continue until satisfied or sick of it.

**Comment by xrotwang** [comment]
I think I like the second option for point 4 above a lot more. We'd expect large inventories to have a lot (or at least some) weird phonemes, so trying to accomodate these would be extra hard. And maybe it is particularly useful to assess the long tail of uncommon phonemes in PHOIBLE if weird phonemes are contrasted with empty slots in diagrams.

**Comment by xrotwang** [comment]
So I started addressing this as part of the `pyclts` package, see https://github.com/cldf-clts/pyclts/issues/14
This seems appropriate, because CLTS provides
- a feature system suitable for slotting phonemes into the charts
- mappings between common transcriptions systems (including partial support for PHOIBLE).

As first proof-of-concept I replaced the custom charts we previously had in APiCS with generic ones based on CLTS/`pyclts`, e.g. https://apics-online.info/contributions/3#tipa

**Comment by LinguList** [comment]
Very nice!

**Comment by drammock** [comment]
@xrotwang you probably already know this, but that sure renders rather badly on phone-sized screens: 
![Screenshot_20200608-065401](https://user-images.githubusercontent.com/1810515/84038814-3da8ac00-a955-11ea-821a-b8b45af00ea6.png)

**Comment by xrotwang** [comment]
I didn't really know, but sort of expected this. But I think that even if the panels wouldn't overlap, the usability would be poor, so fully functional mobile support is a bit of an elusive goal anyway.

**Comment by bambooforest** [comment]
The old charts look good on mobile in that (at least on my device), you
just have to scroll over to see the whole thing.

**Comment by xrotwang** [comment]
@bambooforest the old charts *for APiCS* or for PHOIBLE?

**Comment by bambooforest** [comment]
Sorry, for PHOIBLE. (I guess they aren't old because you haven't updated
them :)
